name: Build & Publish image
on:
  push:
    branches: [main]
  workflow_dispatch:

permissions:
  contents: read
  packages: write          # allow push to GHCR

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to ghcr.io
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build & push
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ghcr.io/byu-acme/vol4-second-container:latest
          platforms: linux/amd64,linux/arm64